version: '3.8'
networks:
   frontend:

services:
   front:
      container_name: front-end
      image: gza73/agh-praca-inzynierska-front-end:latest
      ports:
         - "5000:5000"
      networks:
         - frontend
