name: Continuous delivery

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js '14.x'
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Test
        run: npm test
        
      - name: Build
        run: npm run build --if-present
      
      - name: Build Docker image
        run: docker build -t gza73/agh-praca-inzynierska-front-end .
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-front-end:latest
