name: Continuous integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install_test_build:
    name: Install, test and build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js '14.x'
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
    
    - name: Build
      run: npm run build --if-present
